CREATE TABLE products
(
    product_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT products_pkey PRIMARY KEY,
    code       VARCHAR (255) CONSTRAINT uk_product_code UNIQUE,
    name       VARCHAR (255),
    price      NUMERIC (19, 2)
);

INSERT INTO products(code, name, price) VALUES ('P001', 'M&M', 2.5);
INSERT INTO products(code, name, price) VALUES ('P002', 'Lays Small', 0.75);
INSERT INTO products(code, name, price) VALUES ('P003', 'Lays Medium', 1.75);
INSERT INTO products(code, name, price) VALUES ('P004', 'Lays Large', 2.25);