CREATE TABLE products
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT products_pkey PRIMARY KEY,
    code       VARCHAR (255) CONSTRAINT uk_product_code UNIQUE,
    name       VARCHAR (255),
    price      NUMERIC (19, 2)
);

CREATE TABLE vending_machine
(
    vending_machine_id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vending_machine_pkey PRIMARY KEY ,
    access_attempts    INTEGER,
    access_code        VARCHAR (255),
    code               VARCHAR (255) CONSTRAINT uk_vending_machine_code UNIQUE ,
    last_money_pickup  TIMESTAMP,
    last_ping          TIMESTAMP,
    status             VARCHAR (255),
    type               VARCHAR (255)
);

CREATE TABLE vaults
(
    vault_id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vaults_pkey PRIMARY KEY,
    count                 INTEGER ,
    currency_denomination VARCHAR (255),
    currency_type         VARCHAR (255),
    vending_machine_id    bigint CONSTRAINT fk_vault_vending_machine REFERENCES vending_machine
);

CREATE TABLE transaction_details
(
    transaction_detail_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT transaction_details_pkey PRIMARY KEY ,
    count                 INTEGER ,
    currency_denomination VARCHAR (255),
    currency_type         VARCHAR (255),
    transaction_id        bigint CONSTRAINT fk_transaction_detail_transaction REFERENCES transactions
);

CREATE TABLE transactions
(
    transaction_id     bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT transactions_pkey PRIMARY KEY,
    amount             NUMERIC (19, 2),
    issuer             VARCHAR (255),
    time               TIMESTAMP ,
    type               VARCHAR (255),
    transaction_uuid   VARCHAR (255) CONSTRAINT uk_transaction_uuid UNIQUE ,
    product_id         bigint CONSTRAINT fk_transaction_product REFERENCES products,
    vending_machine_id bigint CONSTRAINT fk_transaction_vending_machine REFERENCES vending_machine
);

CREATE TABLE vending_machine_product
(
    vending_machine_product_id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vending_machine_product_pkey PRIMARY KEY,
    count                      INTEGER ,
    product_id                 bigint CONSTRAINT fk_vending_machine_product_product REFERENCES products,
    vending_machine_id         bigint CONSTRAINT fk_vending_machine_product_vending_machine REFERENCES vending_machine
);

INSERT INTO products(code, name, price) VALUES ('P001', 'M&M', 2.5);
INSERT INTO products(code, name, price) VALUES ('P002', 'Lays Small', 0.75);
INSERT INTO products(code, name, price) VALUES ('P003', 'Lays Medium', 1.75);
INSERT INTO products(code, name, price) VALUES ('P004', 'Lays Large', 2.25);

INSERT INTO vending_machine(access_attempts, access_code, code, last_money_pickup, last_ping, status, type)
VALUES (0, '0000', 'M001', current_timestamp, current_timestamp, 'OK', 'XYZ1');
INSERT INTO vending_machine(access_attempts, access_code, code, last_money_pickup, last_ping, status, type)
VALUES (0, '0000', 'M002', current_timestamp, current_timestamp, 'OK', 'XYZ2');