CREATE TABLE products
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT products_pkey PRIMARY KEY,
    code       VARCHAR (255) CONSTRAINT uk_product_code UNIQUE,
    name       VARCHAR (255),
    price      NUMERIC (19, 2)
);

CREATE TABLE vending_machine
(
    vending_machine_id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vending_machine_pkey PRIMARY KEY ,
    access_attempts    INTEGER,
    access_code        VARCHAR (255),
    code               VARCHAR (255) CONSTRAINT uk_vending_machine_code UNIQUE ,
    last_money_pickup  TIMESTAMP,
    last_ping          TIMESTAMP,
    status             VARCHAR (255),
    type               VARCHAR (255)
);

INSERT INTO products(code, name, price) VALUES ('P001', 'M&M', 2.5);
INSERT INTO products(code, name, price) VALUES ('P002', 'Lays Small', 0.75);
INSERT INTO products(code, name, price) VALUES ('P003', 'Lays Medium', 1.75);
INSERT INTO products(code, name, price) VALUES ('P004', 'Lays Large', 2.25);

INSERT INTO vending_machine(access_attempts, access_code, code, last_money_pickup, last_ping, status, type)
VALUES (0, '0000', 'M001', current_timestamp(), current_timestamp(), 'OK', 'XYZ1');
INSERT INTO vending_machine(access_attempts, access_code, code, last_money_pickup, last_ping, status, type)
VALUES (0, '0000', 'M002', current_timestamp(), current_timestamp(), 'OK', 'XYZ2');